### PR TITLE
Add options parameter to useHotkeys hook

### PR DESCRIPTION
**Pull request by hmafzal**
This fell off my radar, but sending out a PR to address it now!

PR fixes issue #127

### CODE REVIEW

**Comment by JohannesKlauss** [comment]
@hmafzal thx for the PR, I had to lay down programming for a while, but am back now. I will look through the PR next week.

**Comment by hmafzal** [comment]
Sounds good, thanks @JohannesKlauss !

**Comment by adamschoenemann** [comment]
Bump on this one; I definitely need this feature :)

**Comment by rainerbruemmer** [comment]
@JohannesKlauss It would be great, if you could merge this PR. :-)

**Comment by rainerbruemmer** [comment]
Thank you !

**Pull request merged**
